<?php
return [
//    'yii2',
    'yii-core',
    'yii-console',
    'yii-web',
    'yii-rest',

    'yii-project-template',
    'yii-base-web',
    'yii-base-api',
    'yii-base-cli',

    'yii-dataview',
    'yii-queue',
    'yii-dev',
    'yii-bootstrap3',
    'yii-bootstrap4',
    'yii-masked-input',
    'yii-debug',
    'yii-gii',
    'yii-jquery',
    'yii-captcha',
    'yii-swiftmailer',
    'yii-twig',
    'yii-http-client',
    'yii-auth-client',

    'log',
    'di',
    'cache',
    'db',
    'active-record',
    'rbac',

    'db-mysql',
    'db-mssql',
    'db-pgsql',
    'db-sqlite',
    'db-oracle',

    'db-sphinx',
    'db-redis',
    'db-mongodb',
    'db-elasticsearch',
];